Change to use release.namespace and release.name
LM-Development/aks-sample pull request #21
Opened 2023-12-18 16:02 UTC by 1fabi0

This also includes auto generating tcp service config map name and namespace for the ingress controller depending on where it is created

2023-12-19 10:24 UTC, InDieTasten requested changes
Remove that large yaml output from git index, please. Or provide some reason for the file to be tracked.

2023-12-19 10:24 UTC, InDieTasten commented on Samples/PublicSamples/RecordingBot/deploy/teams-recording-bot/result_chart.yaml
Not sure whether we want to really track this file?

2024-01-09 11:56 UTC, InDieTasten submitted a review, later dismissed

2024-01-19 08:27 UTC, rsubrama83 approved these changes

2024-01-30 11:56 UTC, merged