Extract Cert manager from the teams-recording-bot chart
LM-Development/aks-sample pull request #23
Opened 2024-01-08 13:13 UTC by 1fabi0

Remove Cert-Manager from the teams-recording-bot Chart as it is a bad practise with the CRDs of the Cert Manager.
Instead add a folder dedidicated for installing the cert-manager

2024-01-09 12:00 UTC, InDieTasten requested changes

2024-01-09 12:00 UTC, InDieTasten commented on Samples/PublicSamples/RecordingBot/deploy/cert-manager/install.bat
I would prefer bash script

2024-01-11 13:45 UTC, rsubrama83 approved these changes

2024-01-17 08:44 UTC, InDieTasten approved these changes

2024-01-17 12:28 UTC, merged