Code optimized by Copilot
LM-Development/aks-sample pull request #25
Opened 2024-01-30 11:11 UTC by rsubrama83

2024-01-30 11:41 UTC, InDieTasten requested changes
Waiting for previous code changes to be tested before merging this

2024-03-08 11:23 UTC, fde-lmag reviewed
PlatformCallController.OnNotificationRequestAsync
=> AuthenticationProvider.ValidateInboundRequestAsync
=> JwtSecurityTokenHandler.ValidateToken
=> throws Exception
IDX12709: CanReadToken() returned false. JWT is not well formed.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.

2024-03-08 12:35 UTC, fde-lmag reviewed
Seems these changes after merging with main wont work
The branch as is runs into a 401 (JWT parse exception that was fixed on main)
The branch merged with main seems to not work properly (no requests are coming in after accepting a call)

2024-03-11 08:57 UTC, 1fabi0 requested changes

2024-03-11 08:57 UTC, 1fabi0 commented on Samples/PublicSamples/RecordingBot/src/RecordingBot.Services/Bot/CallHandler.cs
> +            if (e.OldResource.State == CallState.Established && e.NewResource.State == CallState.Terminated)
To check for newResource state is enough

2024-03-11 08:57 UTC, 1fabi0 commented on Samples/PublicSamples/RecordingBot/src/RecordingBot.Services/Http/Controllers/PlatformCallController.cs
> +                httpRequestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", Request.Headers.Authorization);
Request.Headers.Authorization needs to be splitted from Bearer( see how it is done in main Branch)

2024-03-20 10:05 UTC, closed without merging